name: travel_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:

  uses-material-design: true
  assets:
   - assets/images/
   - assets/icons/
   - assets/
  fonts:
   - family: Andika
     fonts:
         - asset: assets/fonts/Andika/Andika-Bold.ttf
         - asset: assets/fonts/Andika/Andika-Italic.ttf
         - asset: assets/fonts/Andika/Andika-Regular.ttf
   - family: Poppins
     fonts:
         - asset: assets/fonts/Poppins/Poppins-Black.ttf
         - asset: assets/fonts/Poppins/Poppins-BlackItalic.ttf
         - asset: assets/fonts/Poppins/Poppins-Bold.ttf
         - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
         - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
         - asset: assets/fonts/Poppins/Poppins-ThinItalic.ttf
         - asset: assets/fonts/Poppins/Poppins-SemiBoldItalic.ttf
         - asset: assets/fonts/Poppins/Poppins-Light.ttf
         - asset: assets/fonts/Poppins/Poppins-Italic.ttf
           weight: 700
